### PR TITLE
Add linting via TSLint

### PR DESCRIPTION
**Pull request by jrolfs**
- Add TSLint
- Add TSLint configuration
- Add `lint` NPM script
- Update existing source a bit to conform to configuration

### CODE REVIEW

**Comment by cspotcode** [comment]
Some of these changes conflict with my personal code style.  For example, I want to enforce that there is never a space between `if` and the opening parentheses.

For example, always:
`if(true)`
and never
`if (true)`

Can tslint do that?

**Comment by cspotcode** [comment]
It looks like https://www.npmjs.com/package/tslint-eslint-rules can handle whitespacing the way I was hoping.  I'll test it out.

**Comment by jrolfs** [comment]
Yep, sorry, I meant to leave a comment here asking about your preference. I mostly got going on this because of the bitHound check, heh.

Anyways, I went with the `latest` preset and tried to tune it a bit. Sorry to trample all over your style!

TSLint is definitely quite a bit more limited than ESLint when it comes to these sorts of stylist things, but I have used the plugin you mentioned to gain a bit more control. Unfortunately, it still doesn't provide the ideal *exact* control over this particular spacing but I think a combination of the rules will make do.

**Nice work on this package by the way – thanks for this.** I was really happy to find a well tested implementation of this as it is 99% of the time the only tagged template literal I need instead of pulling in a dependency on a whole library of these.

**Comment by jrolfs** [comment]
From what I can see, it's not possible to *enforce* the absence of whitespace after keywords (`if`, `while`, etc.), but I tried to get the configuration as close as possible to your preferred style.

I think what you'll need is support for the [keyword-spacing](http://eslint.org/docs/rules/keyword-spacing) rule in [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules#stylistic-issues).

**Comment by cspotcode** [comment]
Ah yeah, I misinterpreted their readme and didn't realize that rule is
unsupported.  Now I'm looking at typescript-formatter's --verify flag.  It
uses the TypeScript compiler's built-in code formatter which supports a few
more whitespacing options.  Fingers crossed.

Thanks again for the PR, I think I'll be able to tweak it a bit and then
merge.

**Comment by jrolfs** [comment]
Ah, nice find! I think `"insertSpaceAfterKeywordsInControlFlowStatements": false` might get you the keyword spacing you're looking for. Hopefully that's all you need in addition to this :)

**Pull request closed without merging**
