### PR TITLE
fix: webpack bundling [#9]

### LINKED ISSUE #9: outdent lib-module check for 'module' breaks code bundled with webpack
I'm not _entirely_ sure what's going on, but I'm using `outdent` in a project that's built using [next.js](https://github.com/zeit/next.js) (and hence webpack), and the built code has broken on upgrading from outdent 0.3.0 to 0.5.0.

The browser error includes these lines:

```
ReferenceError: exports is not defined
    at Object.<anonymous> (http://localhost:3000/_next/-/page/foo.js:7394:30)
    at Object../node_modules/outdent/lib-module/index.js (http://localhost:3000/_next/-/page/foo.js:7401:30)
    at __webpack_require__ (http://localhost:3000/_next/-/manifest.js:715:31)
```
The JS built by webpack incorporates the `outdent/lib-module/index.js` file like this (I've omitted the irrelevant bits of the `foo.js` file):

```js
/***/ "./node_modules/outdent/lib-module/index.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* WEBPACK VAR INJECTION */(function(module) {/* unused harmony export outdent */
// In the absence of a WeakSet or WeakMap implementation, don't break, but don't cache either.

// ...lots omitted here...

// Named exports.  Simple and preferred.
/* harmony default export */ __webpack_exports__["a"] = (outdent);

if (true) {
    module.exports = exports = outdent;
    // TODO is this necessary?
    Object.defineProperty(outdent, '__esModule', { value: true });
    outdent.default = outdent;
    outdent.outdent = outdent;
}
//# sourceMappingURL=index.js.map
/* WEBPACK VAR INJECTION */}.call(__webpack_exports__, __webpack_require__("./node_modules/webpack/buildin/harmony-module.js")(module)))

```

You'll see that the original code's check `if (typeof module !== 'undefined')` has been optimised to `if (true)`, presumably as `module` exists -- but there's no `exports` variable, so the code explodes.

Is there a better check you could do on that line to achieve the desired effect?

### PR DESCRIPTION
**Pull request by chasemccoy**
@cspotcode This fixes #9. After making this change I ran the tests and linked the package locally to test the fix. Everything is working properly for me again.

### CODE REVIEW

**Comment by chasemccoy** [comment]
Looks like this may not work with SSR in Gatsby though...

**Comment by cspotcode** [comment]
@chasemccoy What is SSR in Gatsby?

**Comment by cspotcode** [comment]
Fixed in v0.6.0.  I couldn't merge this PR because the real fix was slightly different.  I added a test for webpack bundling.  If you use a different bundler that's not working, you can PR a failing test and I'll take a look.

**Comment by chasemccoy** [comment]
Thanks!

**Pull request closed without merging**
